import { cn } from "@/lib/utils";
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "@/components/Navbar";
// import { SessionProvider } from 'next-auth/react'
// import { Provider as WagmiProvider } from 'wagmi'
import Providers from './_providers/providers'
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Project C',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      <body className={cn(inter.className, "antialiased min-h-screen pt-16")}>
      <Providers>
        <ThemeProvider>
        <Navbar/>
        {children}
        <Toaster/>
        </ThemeProvider>
        </Providers>
        </body>
    </html>
  )
}
